<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241129085430 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE etudiant_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE semestre_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE matiere_id_seq CASCADE');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE matiere DROP CONSTRAINT matiere_idsemestre_fkey');
        $this->addSql('ALTER TABLE inscription DROP CONSTRAINT inscription_idetudiant_fkey');
        $this->addSql('ALTER TABLE inscription DROP CONSTRAINT inscription_idsemestre_fkey');
        $this->addSql('ALTER TABLE notes DROP CONSTRAINT notes_id_idetudiant_fkey');
        $this->addSql('ALTER TABLE notes DROP CONSTRAINT notes_idmatiere_fkey');
        $this->addSql('DROP TABLE matiere');
        $this->addSql('DROP TABLE semestre');
        $this->addSql('DROP TABLE inscription');
        $this->addSql('DROP TABLE notes');
        $this->addSql('DROP TABLE etudiant');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE etudiant_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE semestre_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE matiere_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE matiere (id INT DEFAULT matiere_id_seq NOT NULL, nom VARCHAR(50) NOT NULL, credit INT NOT NULL, idsemestre INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9014574ADBBDC7B1 ON matiere (idsemestre)');
        $this->addSql('CREATE TABLE semestre (id INT DEFAULT semestre_id_seq NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE inscription (idetudiant INT NOT NULL, idsemestre INT NOT NULL, paye NUMERIC(15, 2) NOT NULL, daty DATE DEFAULT NULL, PRIMARY KEY(idetudiant, idsemestre))');
        $this->addSql('CREATE INDEX IDX_5E90F6D6DBAB6AEE ON inscription (idetudiant)');
        $this->addSql('CREATE INDEX IDX_5E90F6D6DBBDC7B1 ON inscription (idsemestre)');
        $this->addSql('CREATE TABLE notes (id_idetudiant INT NOT NULL, idmatiere INT NOT NULL, note NUMERIC(15, 2) DEFAULT NULL, session DATE DEFAULT NULL, PRIMARY KEY(id_idetudiant, idmatiere))');
        $this->addSql('CREATE INDEX IDX_11BA68C7E21EA39 ON notes (id_idetudiant)');
        $this->addSql('CREATE INDEX IDX_11BA68C4F100524 ON notes (idmatiere)');
        $this->addSql('CREATE TABLE etudiant (id INT DEFAULT etudiant_id_seq NOT NULL, nom VARCHAR(250) NOT NULL, prenom VARCHAR(250) NOT NULL, datenaissance DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE matiere ADD CONSTRAINT matiere_idsemestre_fkey FOREIGN KEY (idsemestre) REFERENCES semestre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE inscription ADD CONSTRAINT inscription_idetudiant_fkey FOREIGN KEY (idetudiant) REFERENCES etudiant (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE inscription ADD CONSTRAINT inscription_idsemestre_fkey FOREIGN KEY (idsemestre) REFERENCES semestre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notes ADD CONSTRAINT notes_id_idetudiant_fkey FOREIGN KEY (id_idetudiant) REFERENCES etudiant (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notes ADD CONSTRAINT notes_idmatiere_fkey FOREIGN KEY (idmatiere) REFERENCES matiere (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
